### ISSUE TITLE
FTP file open is broken

### ISSUE THREAD

**Issue by ahcub** [intake/filesystem_spec#197]
a simple try to open a file using ftp like the following

```
import fsspec
fs = fsspec.filesystem('ftp', host='hostname', port=21, username='test', password='test')
print(fs.open('/root/test.csv'))

```
results into an error like this

```Traceback (most recent call last):
  File "C:/Users/trader/.PyCharm2019.2/config/scratches/scratch_1.py", line 5, in <module>
    print(fs.open('///sim/test.csv'))
  File "C:\Users\trader\Miniconda3\envs\p3\lib\site-packages\fsspec\spec.py", line 708, in open
    path, mode=mode, block_size=block_size, autocommit=ac, **kwargs
  File "C:\Users\trader\Miniconda3\envs\p3\lib\site-packages\fsspec\implementations\ftp.py", line 133, in _open
    autocommit=autocommit,
  File "C:\Users\trader\Miniconda3\envs\p3\lib\site-packages\fsspec\implementations\ftp.py", line 170, in __init__
    super().__init__(fs, path, **kwargs)
  File "C:\Users\trader\Miniconda3\envs\p3\lib\site-packages\fsspec\spec.py", line 875, in __init__
    self.details = fs.info(path)
  File "C:\Users\trader\Miniconda3\envs\p3\lib\site-packages\fsspec\implementations\ftp.py", line 122, in info
    return [f for f in files if f["name"] == path][0]
IndexError: list index out of range
```

because the `self._parent('/root/test.csv')` returns `'//root'` instead of `'/root'`
and then `self.ls('//root', True)` returns the list of `'/'` directory instead of `'/root'`

that affects dask as it fails with the same error when trying to open files via ftp

**Comment by TomAugspurger** [comment]
Hmm, does the following fail for you? It passes for me

```diff
diff --git a/fsspec/implementations/tests/test_ftp.py b/fsspec/implementations/tests/test_ftp.py
index 91968fb..c265ceb 100644
--- a/fsspec/implementations/tests/test_ftp.py
+++ b/fsspec/implementations/tests/test_ftp.py
@@ -114,3 +114,13 @@ def test_transaction(ftp_writable):
 
     fs.rm(fn)
     assert not fs.exists(fn)
+
+
+def test_read(ftp_writable):
+    host, port, user, pw = ftp_writable
+    fs = FTPFileSystem(host, port, user, pw)
+
+    with fs.open('/out') as f:
+        result = f.read()
+
+    assert result
```

**Comment by ahcub** [comment]
yep, same error traceback as I mentioned in the issue

**Comment by ahcub** [comment]
I have a different path structure tho, can you try `/dir/out`?

**Comment by ahcub** [comment]
the root paths work without issue most likely, at least according to what I saw

**Comment by TomAugspurger** [comment]
```diff
diff --git a/docs/source/changelog.rst b/docs/source/changelog.rst
index da4a4ae..c6f2168 100644
--- a/docs/source/changelog.rst
+++ b/docs/source/changelog.rst
@@ -20,4 +20,5 @@ Version 0.6.0
 * Improved handling of requests for :class:`fsspec.implementations.http.HTTPFileSystem` when the
   HTTP server responds with an (incorrect) content-length of 0 (:pr:`163`)
 * Added a ``detail=True`` parameter to :meth:`fsspec.spec.AbstractFileSystem.ls` (:pr:`168`)
-* Fixed handling of UNC/DFS paths (:issue:`154`)
\ No newline at end of file
+* Fixed handling of UNC/DFS paths (:issue:`154`)
+* Increased the minimum required version of fsspec to 0.6.0
\ No newline at end of file
diff --git a/fsspec/implementations/tests/test_ftp.py b/fsspec/implementations/tests/test_ftp.py
index 91968fb..babe0dc 100644
--- a/fsspec/implementations/tests/test_ftp.py
+++ b/fsspec/implementations/tests/test_ftp.py
@@ -114,3 +114,20 @@ def test_transaction(ftp_writable):
 
     fs.rm(fn)
     assert not fs.exists(fn)
+
+
+def test_read(ftp_writable):
+    host, port, user, pw = ftp_writable
+    fs = FTPFileSystem(host, port, user, pw)
+
+    fs.mkdir("/a")
+    fs.mkdir("/a/b")
+    data = b"0" * 10
+    with fs.open("/a/b/file.txt", "wb") as f:
+        f.write(data)
+
+    fs.invalidate_cache()
+
+    with fs.open('/a/b/file.txt') as f:
+        result = f.read()
+    assert result == data
```

Same thing. I wonder if this is a windows-only issue (I'm on MacOS).

**Comment by ahcub** [comment]
hm, strange
I ran it on both Windows and in Jupyter Notebook which runs on Linux.

**Comment by ahcub** [comment]
maybe I should try to run it on the master version of the codebase and see if it reproduces, not sure

**Comment by martindurant** [comment]
Closing as stale
