### ISSUE TITLE
issue with cache_options in 0.6.0 using intake.upload with azure datalake

### ISSUE THREAD

**Issue by JoranDox** [intake/filesystem_spec#205]
Traceback (most recent call last):
  File "/home/vsts/work/1/s/machine_readable_spec/transformations/push_to_datalake.py", line 38, in <module>
    entry = intake.upload([infile_read], outloc_latest, storage_options=global_storage_options)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/intake/container/__init__.py", line 54, in upload
    s = cls._data_to_source(data, path, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/intake/container/semistructured.py", line 95, in _data_to_source
    dask.compute(out)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/dask/threaded.py", line 81, in get
    **kwargs
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/intake/container/semistructured.py", line 101, in write_file
    with fo as f:
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/fsspec/core.py", line 98, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/fsspec/spec.py", line 725, in open
    **kwargs
TypeError: _open() got an unexpected keyword argument 'cache_options'
##[error]/opt/hostedtoolcache/Python/3.7.5/x64/bin/python failed with return code: 1

pip freeze:

attrs==19.3.0
azure-common==1.1.23
azure-datalake-store==0.0.48
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
boltons==19.3.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cloudpickle==1.2.2
cryptography==2.8
dask==2.7.0
entrypoints==0.3
fsspec==0.6.0
idna==2.8
importlib-metadata==0.23
intake==0.5.3+36.gba252a0
Jinja2==2.10.3
jsonschema==3.1.1
locket==0.2.0
MarkupSafe==1.1.1
more-itertools==7.2.0
msgpack==0.6.2
numpy==1.17.4
pandas==0.25.3
partd==1.0.0
pyarrow==0.15.1
pycparser==2.19
PyJWT==1.7.1
pyrsistent==0.15.5
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.1.2
requests==2.22.0
six==1.13.0
toolz==0.10.0
urllib3==1.25.7
zipp==0.6.0

I'm not sure what other things I can add as extra info, if there is anything, please let me know

**Comment by JoranDox** [comment]
For clarity: it worked with the same installs & code except for fsspec==0.5.2

**Comment by hayesgb** [comment]
This was caused by missing **kwargs in the _open method for adlfs, which should be in the current version.  I encountered it when using the distributed library.
