### ISSUE TITLE
PermissionError on Windows when using LocalFileSystem.transaction

### ISSUE THREAD

**Issue by dhirschfeld** [intake/filesystem_spec#229]
```python
from fsspec.implementations.local import LocalFileSystem


fs = LocalFileSystem()

with fs.open('data.txt', 'w') as f:
    f.write('ABC')

with fs.transaction:
    with fs.open('data.txt', 'w') as f:
        f.write('DEF')
```
```python-traceback
Traceback (most recent call last):

  File "<ipython-input-9-afc4aa1abe2e>", line 3, in <module>
    f.write('DEF')

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\transaction.py", line 24, in __exit__
    self.complete(commit=exc_type is None)

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\transaction.py", line 36, in complete
    f.commit()

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\fsspec\implementations\local.py", line 219, in commit
    os.rename(self.temp, self.path)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\dhirschf\\AppData\\Local\\Temp\\2\\tmpa03bxzd_' -> 'C:/Users/dhirschf/code/sandbox/data.txt'
```

**Comment by dhirschfeld** [comment]
***Note:*** This works fine without the transaction so it appears that the transaction is keeping an open handle to the file?

At the point of the exception the `self.f` attribute points to the temp file which appears to be closed:
```python
self
Out[2]: <fsspec.implementations.local.LocalFileOpener at 0x21e1be53c08>
self.fs
Out[3]: <fsspec.implementations.local.LocalFileSystem at 0x21e1a2be548>
self.f
Out[4]: <_io.BufferedWriter name='C:\\Users\\dhirschf\\AppData\\Local\\Temp\\2\\tmphtjujnel'>
self.f.closed
Out[5]: True
```

**Comment by martindurant** [comment]
I have looked a little, and so far not found why the rename is blocked. Deleting the file is also blocked, in the case of an exception in the transaction context.

**Comment by dhirschfeld** [comment]
Yeah, I haven't had any luck tracking it down so far. File locking on Windows is a nasty can of worms :/

**Comment by martindurant** [comment]
If you are interested, `i, name = tempfile.mkstemp()` was the culprit - this uses `os.open` and the file does not get closed by the garbage collector.

**Comment by dhirschfeld** [comment]
Thanks for following up! I can only imagine that was a tough one to track down!
