### ISSUE TITLE
recursive put behaving incorrectly for absolute paths

### ISSUE THREAD

**Issue by dynamix** [intake/filesystem_spec#281]
I'm having a filesystem object which is either a `LocalFileSystem` or a `GCSFileSystem`. In both cases I want to use `put` to copy a directory recursively from a local source to a target location (either locally or in the cloud).   

Due to https://github.com/intake/filesystem_spec/blob/master/fsspec/spec.py#L628-L633 the resulting path is incorrect. The absolute paths shouldn't be concatenated?

```Python
import fsspec
import os

print(fsspec.__version__)
print(os.getcwd())

fs = fsspec.filesystem("file")
fs.mkdirs("/tmp/example", exist_ok=True)
fs.mkdirs("/tmp/target", exist_ok=True)
fs.touch("/tmp/example/foo.txt")
fs.put("/tmp/example", "/tmp/target", recursive=True)
```

Output:
```
0.7.2
/private/tmp/test
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    fs.put("/tmp/example", "/tmp/target", recursive=True)
  File "/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 91, in put
    return super(LocalFileSystem, self).put(path1, path2, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fsspec/spec.py", line 647, in put
    with self.open(rpath, "wb", **kwargs) as f2:
  File "/usr/local/lib/python3.7/site-packages/fsspec/spec.py", line 775, in open
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 108, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 175, in __init__
    self._open()
  File "/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py", line 180, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/test/example/foo.txt'
```

**Comment by martindurant** [comment]
What do you think of the following fix?
```diff
--- a/fsspec/spec.py
+++ b/fsspec/spec.py
@@ -625,9 +625,7 @@ class AbstractFileSystem(up, metaclass=_Cached):
                     make_path_posix(os.path.join(dirname, filename))
                     for filename in filelist
                 ]
-            rootdir = make_path_posix(
-                os.path.basename(make_path_posix(lpath).rstrip("/"))
-            )
+            rootdir = os.path.basename(make_path_posix(lpath).rstrip("/"))
             if self.exists(rpath):
                 # copy lpath inside rpath directory
                 rpath2 = posixpath.join(rpath, rootdir)
@@ -644,6 +642,7 @@ class AbstractFileSystem(up, metaclass=_Cached):
             rpaths = [rpath]
         for lpath, rpath in zip(lpaths, rpaths):
             with open(lpath, "rb") as f1:
+                self.mkdirs(os.path.dirname(rpath), exist_ok=True)
                 with self.open(rpath, "wb", **kwargs) as f2:
                     data = True
```

Note that, since the target directory already exists, in this case the whole source directory ends up within the target.

**Comment by dynamix** [comment]
Ah nice, thanks. That works and is in sync with what I would expect. My use-case is to copy only the content of the folder and not the folder itself. Adding another `/` to the source should cause that behaviour. 

It tried to create a PR + some tests:  https://github.com/intake/filesystem_spec/pull/284
I had to touch `MemoryFileSystem` as it did not handle directories correctly in `exists` https://github.com/dynamix/filesystem_spec/blob/86a7922de99b2bb970b2c78c8831752d69f81ad5/fsspec/implementations/memory.py#L83-L99  (does not check `pseudo_dirs`.)
