### ISSUE TITLE
LocalFileSystem recursion error on open file depickle

### ISSUE THREAD

**Issue by ahirner** [intake/filesystem_spec#300]
`fsspec==0.7.4`
`distributed==2.6.0`
`cloudpickle==1.4.1`
## Repro
```python
from dask.distributed import Client
from fsspec.implementations.local import LocalFileSystem

def dump(f):
   with f:
       r = f.read()
   print(r)
   return r

def main():
    with open("f.bin", "wb") as f:
        f.write(b"1234")

    fs = LocalFileSystem("./")
    f = fs.open("f.bin", "rb")

    with Client() as c:
        ff = c.map(dump, [f]*10)
        rr = c.gather(ff)
        c.close()

    print("rr", rr)

if __name__=="__main__":
    main()
```
## Error
```
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "~/miniconda3/lib/python3.6/site-packages/distributed/worker.py", line 2340, in _maybe_deserialize_task
    function, args, kwargs = _deserialize(*self.tasks[key])
  File "~/miniconda3/lib/python3.6/site-packages/distributed/worker.py", line 3132, in _deserialize
    args = pickle.loads(args)
  File "~/miniconda3/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
  File "~/miniconda3/lib/python3.6/site-packages/fsspec/implementations/local.py", line 214, in __setstate__
    loc = self.state.pop("loc")
  File "~/miniconda3/lib/python3.6/site-packages/fsspec/implementations/local.py", line 246, in __getattr__
    return getattr(self.f, item)
  File "~/miniconda3/lib/python3.6/site-packages/fsspec/implementations/local.py", line 246, in __getattr__
    return getattr(self.f, item)
  File "~/miniconda3/lib/python3.6/site-packages/fsspec/implementations/local.py", line 246, in __getattr__
    return getattr(self.f, item)
  [Previous line repeated 320 more times]
RecursionError: maximum recursion depth exceeded~
```
## Expected
Hopefully this is case is not beyond the spec of fsspec. Since all pickle relevant methods are so well thought through I'd be happy if this works out.
I think `self.f` should be set at depickling time and hence there should not be recursion... yet there is.

**Comment by martindurant** [comment]
Thanks for posting. Note that the usual expectation is to pass `OpenFile` objects, which would look like
```
of = filesystem.open("f.bin", "rb")  # ("file://" protocol is optional)
```
which only actually opens the file in the `with` block.

Of course, what you are doing should work too, hence the linked PR.

**Comment by ahirner** [comment]
Brilliant, that fixed the problem!
We sometimes need to pass filesystems around, hence the pattern of above.
