### ISSUE TITLE
open_local always fails on first call but loads on following calls

### ISSUE THREAD

**Issue by eric-czech** [intake/filesystem_spec#311]
I am seeing this same behavior with a variety of public GCS files (of varying sizes) where the first call to `open_local` fails 100% of the time and subsequent calls *almost* always succeed.  Sometimes they fail as well, but either way I have yet to see one case where changing `cache_storage` in this example doesn't then cause an error on the following run of the same code:

```python
import fsspec
fsspec.open_local(
  'simplecache::gs://public-data-source/README.md', 
  simplecache={'cache_storage': '/tmp/cache'}, 
  gcs={'anon': True}
)
_call non-retriable exception: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/gcsfs/core.py", line 487, in _call
    validate_response(r, path)
  File "/opt/conda/lib/python3.7/site-packages/gcsfs/core.py", line 132, in validate_response
    raise HttpError({"code": r.status_code})
gcsfs.utils.HttpError
```
<details>
<summary>Full Trace</summary>
_call non-retriable exception: 
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/gcsfs/core.py", line 487, in _call
    validate_response(r, path)
  File "/opt/conda/lib/python3.7/site-packages/gcsfs/core.py", line 132, in validate_response
    raise HttpError({"code": r.status_code})
gcsfs.utils.HttpError
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
<ipython-input-67-6101ab786208> in <module>
      1 #%%debug
      2 url = 'simplecache::gs://public-data-source/README.md'
----> 3 fsspec.open_local(url, simplecache={'cache_storage': '/tmp/cache7'}, gcs={'anon': True})

/opt/conda/lib/python3.7/site-packages/fsspec/core.py in open_local(url, mode, **storage_options)
    397         raise ValueError("Can only ensure local files when reading")
    398     of = open_files(url, mode=mode, **storage_options)
--> 399     paths = [f.open().name for f in of]
    400     if isinstance(url, str) and "*" not in url:
    401         return paths[0]

/opt/conda/lib/python3.7/site-packages/fsspec/core.py in <listcomp>(.0)
    397         raise ValueError("Can only ensure local files when reading")
    398     of = open_files(url, mode=mode, **storage_options)
--> 399     paths = [f.open().name for f in of]
    400     if isinstance(url, str) and "*" not in url:
    401         return paths[0]

/opt/conda/lib/python3.7/site-packages/fsspec/core.py in open(self)
    130         been deleted; but a with-context is better style.
    131         """
--> 132         out = self.__enter__()
    133         closer = out.close
    134         fobjects = self.fobjects.copy()[:-1]

/opt/conda/lib/python3.7/site-packages/fsspec/core.py in __enter__(self)
     98         mode = self.mode.replace("t", "").replace("b", "") + "b"
     99 
--> 100         f = self.fs.open(self.path, mode=mode)
    101 
    102         self.fobjects = [f]

/opt/conda/lib/python3.7/site-packages/fsspec/implementations/cached.py in <lambda>(*args, **kw)
    314             # all the methods defined in this class. Note `open` here, since
    315             # it calls `_open`, but is actually in superclass
--> 316             return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
    317         if item in ["__reduce_ex__"]:
    318             raise AttributeError

/opt/conda/lib/python3.7/site-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    773                 autocommit=ac,
    774                 cache_options=cache_options,
--> 775                 **kwargs
    776             )
    777             if not ac:

/opt/conda/lib/python3.7/site-packages/fsspec/implementations/cached.py in <lambda>(*args, **kw)
    314             # all the methods defined in this class. Note `open` here, since
    315             # it calls `_open`, but is actually in superclass
--> 316             return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
    317         if item in ["__reduce_ex__"]:
    318             raise AttributeError

/opt/conda/lib/python3.7/site-packages/fsspec/implementations/cached.py in _open(self, path, mode, **kwargs)
    495                 data = True
    496                 while data:
--> 497                     data = f.read(f.blocksize)
    498                     f2.write(data)
    499             else:

/opt/conda/lib/python3.7/site-packages/fsspec/spec.py in read(self, length)
   1237             # don't even bother calling fetch
   1238             return b""
-> 1239         out = self.cache._fetch(self.loc, self.loc + length)
   1240         self.loc += len(out)
   1241         return out

/opt/conda/lib/python3.7/site-packages/fsspec/caching.py in _fetch(self, start, end)
     30 
     31     def _fetch(self, start, end):
---> 32         return self.fetcher(start, end)
     33 
     34     def __getitem__(self, item: slice):

/opt/conda/lib/python3.7/site-packages/gcsfs/core.py in _fetch_range(self, start, end)
   1213             head = None
   1214         try:
-> 1215             r = self.gcsfs._call("GET", self.details["mediaLink"], headers=head)
   1216             data = r.content
   1217             return data

/opt/conda/lib/python3.7/site-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    502                     continue
    503                 logger.exception("_call non-retriable exception: %s", e)
--> 504                 raise e
    505 
    506         return r

/opt/conda/lib/python3.7/site-packages/gcsfs/core.py in _call(self, method, path, *args, **kwargs)
    485                     timeout=self.requests_timeout,
    486                 )
--> 487                 validate_response(r, path)
    488                 break
    489             except (HttpError, RequestException, GoogleAuthError) as e:

/opt/conda/lib/python3.7/site-packages/gcsfs/core.py in validate_response(r, path)
    130             raise HttpError(error)
    131         elif r.status_code:
--> 132             raise HttpError({"code": r.status_code})
    133         else:
    134             raise RuntimeError(m)

HttpError: 
</details>

Then on the next run:

```python
fsspec.open_local(
  'simplecache::gs://public-data-source/README.md', 
  simplecache={'cache_storage': '/tmp/cache'}, 
  gcs={'anon': True}
)
> /tmp/cache7/e765909a3e2d87ed1557be40d63eb40b0070a7f234b4b9b626a965598c8ad286
```

When I switch to `filecache` (and change `cache_storage` to a different directory entirely), I see the same behavior except that it often fails on subsequent runs too if I wait ~10 seconds or so.

Any idea what's going on here?

----
#### Environment

```bash
> conda list | grep 'fsspec\|gcsfs'
fsspec                    0.7.4                      py_0    conda-forge
gcsfs                     0.6.2                      py_0    conda-forge
> python --version
Python 3.7.6
```

**Comment by eric-czech** [comment]
Another thing I've noticed is that if I use a larger file (~80M) like this:

```python
url = 'simplecache::gs://public-data-source/catalog/clinvar/v1.0-20200607/submission_summary.parquet'
fsspec.open_local(url, simplecache={'cache_storage': '/tmp/simplecache'})
```

it will download the file for 10 seconds or so and then throw the error in the OP.  On the next run, I get the cached path instantly and the data at the path is fine (I can count rows in the parquet table via Spark).  It seems almost like the error is being thrown when a stream somewhere is being closed.

FWIW, the http error code coming back is 416.

**Comment by martindurant** [comment]
The specific error is: that the download is attempting to fetch one more block beyond the end of the file (i.e., when you already have all the bytes). I don't yet know why this is happening the loop seems like it should work:
```python
                data = True
                while data:
                    data = f.read(f.blocksize)
                    f2.write(data)
```

**Comment by martindurant** [comment]
I suggest the following change:
```python
--- a/fsspec/caching.py
+++ b/fsspec/caching.py
@@ -28,34 +28,14 @@ class BaseCache(object):
         self.fetcher = fetcher
         self.size = size

-    def _fetch(self, start, end):
-        return self.fetcher(start, end)
-
-    def __getitem__(self, item: slice):
-        if not isinstance(item, slice):
-            raise TypeError(
-                "Cache indices must be a contiguous slice. Got {} instead.".format(
-                    type(item)
-                )
-            )
-        if item.step and item.step != 1:
-            raise ValueError(
-                "Cache indices must be a contiguous slice. 'item' has step={}".format(
-                    item.step
-                )
-            )
-
-        # handle endpoints
-        if item.start is None:
-            item = slice(0, item.stop)
-        elif item.start < 0:
-            item = slice(self.size + item.start, item.stop)
-        if item.stop is None:
-            item = slice(item.start, self.size)
-        elif item.stop < 0:
-            item = slice(item.start, self.size + item.stop)
-
-        return self._fetch(item.start, item.stop)
+    def _fetch(self, start, stop):
+        if start is None:
+            start = 0
+        if stop is None:
+            stop = self.size
+        if start >= self.size or start >= stop:
+            return b""
+        return self.fetcher(start, stop)
```

**Comment by martindurant** [comment]
(note that the cache getitem is tested in test_caches, but not actually used anywhere in the code)
