### ISSUE TITLE
Can't cache a github:// url

### ISSUE THREAD

**Issue by sodre** [intake/filesystem_spec#329]
As a user of intake, I would like to cache files stored in github. Unfortunately, this does not work broken with fsspec 0.7.4 from conda-forge. Here is the exception that is being raised:

```python-traceback
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fsspec
>>> github_url="github://intake:filesystem_spec@master/README.md"
>>> fsspec.open(github_url)
<OpenFile 'README.md'>
>>> fsspec.open(f"simplecache::{github_url}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/core.py", line 370, in open
    return open_files(
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/core.py", line 242, in open_files
    fs, fs_token, paths = get_fs_token_paths(
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/core.py", line 523, in get_fs_token_paths
    fs = cls(**options)
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/spec.py", line 54, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 444, in __init__
    super().__init__(**kw)
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 113, in __init__
    self.fs = fs if fs is not None else filesystem(target_protocol, **self.kwargs)
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/registry.py", line 215, in filesystem
    return cls(**storage_options)
  File "/home/pcarlos/.conda/envs/dev/lib/python3.8/site-packages/fsspec/spec.py", line 54, in __call__
    obj = super().__call__(*args, **kwargs)
TypeError: __init__() missing 2 required positional arguments: 'org' and 'repo'
>>> 
```

:scroll: The actual catalog uses a stable `SHA` instead of `master`, and it needs to reference files in different github organizations and repositories within the same intake data source.

**Comment by martindurant** [comment]
You have found an edge case!
When using `open`, `fsspec` pulls apart a URL to get some arguments like org/repo here, but apparently this isn't happening in a compound URL like your example. This should be easy to fix, if you happen to have the time.
Note that you can work around it now by passing the arguments explicitly:
```python
fsspec.open(f"simplecache::github:///README.md", 
    github={'org': 'intake', 'repo': 'filesystem_spec', 'ref': 'master'})
```
