### ISSUE TITLE
bug: open_local second time after cache dir got deleted fails

### ISSUE THREAD

**Issue by aaronspring** [intake/filesystem_spec#361]
```python
import fsspec as fs
import os
import shutil
url = 'http://maps.tnc.org/files/shp/MEOW-TNC.zip'
lurl = fs.open_local(f'simplecache::{url}', simplecache={'same_names':True, 'cache_storage': 'cache'})
assert os.path.exists(lurl)
lurl
['cache/MEOW-TNC.zip']

# remove cache dir
shutil.rmtree('cache')
assert not os.path.exists(lurl)

# access second time
# except to reload
lurl = fs.open_local(f'simplecache::{url}', simplecache={'same_names':True, 'cache_storage': 'cache'})
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/core.py", line 420, in open_local
    paths = [f.open().name for f in of]
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/core.py", line 420, in <listcomp>
    paths = [f.open().name for f in of]
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/core.py", line 133, in open
    out = self.__enter__()
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/core.py", line 101, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/implementations/cached.py", line 363, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/spec.py", line 844, in open
    **kwargs
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/implementations/cached.py", line 363, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/implementations/cached.py", line 534, in _open
    with self.fs._open(path, **kwargs) as f, open(fn, "wb") as f2:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/MEOW-TNC.zip'
```

**Comment by aaronspring** [comment]
great. how do I cache now remote urls as in the example above?

```
>>> lurl = fs.open_local(f'simplecache::{url}', simplecache={'cache_storage': 'cache','same_names':True})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaron.spring/anaconda3/envs/xr/lib/python3.7/site-packages/fsspec/core.py", line 422, in open_local
    "open_local can only be used on a filesystem which"
ValueError: open_local can only be used on a filesystem which has attribute local_file=True
```

I liked the behaviour that `open_local()` caches results and opens the cached file.

**Comment by aaronspring** [comment]
also `intake-xarray` rely on this behaviour: https://github.com/intake/intake-xarray/blob/bf98a3c69eea81be716b310e33aeefbf1a89b1d0/intake_xarray/netcdf.py#L79

**Comment by martindurant** [comment]
Sorry about that, the test I wrote was unfortunate. #363 will fix, feel free to check.

**Comment by aaronspring** [comment]
works like expected thanks
