### ISSUE TITLE
Change in http implementation of isdir() ?

### ISSUE THREAD

**Issue by joshmoore** [intake/filesystem_spec#375]
The python Zarr client was previously working together with our HTTP-based implementation. (https://github.com/ome/omero-ms-zarr), but a recent change seems to have changed the expectations of a directory listing.

---- 

Test environment:

```
conda create -n fsspec -c conda-forge zarr fsspec dask s3fs aiohttp requests

dask-2.22.0          | 4 KB      | ############################################################################################ | 100%
yarl-1.3.0           | 126 KB    | ############################################################################################ | 100%
multidict-4.7.5      | 60 KB     | ############################################################################################ | 100%
attrs-19.3.0         | 35 KB     | ############################################################################################ | 100%
idna-2.10            | 52 KB     | ############################################################################################ | 100%
markupsafe-1.1.1     | 25 KB     | ############################################################################################ | 100%
pyyaml-5.3.1         | 176 KB    | ############################################################################################ | 100%
dask-core-2.22.0     | 624 KB    | ############################################################################################ | 100%
distributed-2.22.0   | 1.0 MB    | ############################################################################################ | 100%
botocore-1.17.42     | 4.0 MB    | ############################################################################################ | 100%
pandas-1.1.0         | 10.2 MB   | ############################################################################################ | 100%
sqlite-3.32.3        | 1.7 MB    | ############################################################################################ | 100%
setuptools-49.6.0    | 955 KB    | ############################################################################################ | 100%
urllib3-1.25.10      | 92 KB     | ############################################################################################ | 100%
tk-8.6.10            | 3.3 MB    | ############################################################################################ | 100%
async-timeout-3.0.1  | 11 KB     | ############################################################################################ | 100%
cytoolz-0.10.1       | 365 KB    | ############################################################################################ | 100%
psutil-5.7.2         | 345 KB    | ############################################################################################ | 100%
cffi-1.14.1          | 218 KB    | ############################################################################################ | 100%
tornado-6.0.4        | 642 KB    | ############################################################################################ | 100%
aiohttp-3.6.2        | 593 KB    | ############################################################################################ | 100%
docutils-0.15.2      | 737 KB    | ############################################################################################ | 100%
bokeh-2.1.1          | 7.0 MB    | ############################################################################################ | 100%
boto3-1.14.42        | 69 KB     | ############################################################################################ | 100%
s3transfer-0.3.3     | 91 KB     | ############################################################################################ | 100%
cloudpickle-1.5.0    | 22 KB     | ############################################################################################ | 100%
libpng-1.6.37        | 319 KB    | ############################################################################################ | 100%
fsspec-0.8.0         | 61 KB     | ############################################################################################ | 100%
pycparser-2.20       | 94 KB     | ############################################################################################ | 100%
cryptography-3.0     | 619 KB    | ############################################################################################ | 100%
sortedcontainers-2.2 | 25 KB     | ############################################################################################ | 100%
```

with @martindurant `fsspec` branch of zarr-python installed on top.  

HTTP output:

```
(fsspec) ~ $curl -q http://localhost:8080/image/1.zarr/ | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   250  100   250    0     0   2475      0 --:--:-- --:--:-- --:--:--  2500
<?xml version="1.0"?>
<html>
  <head>
    <title>Image #1</title>
  </head>
  <body>
    <h1>Directory listing for Image #1</h1>
    <ul>
      <li>
        <a href=".zattrs">.zattrs</a>
      </li>
      <li>
        <a href=".zgroup">.zgroup</a>
      </li>
      <li>
        <a href="masks/">masks/</a>
      </li>
      <li>
        <a href="0/">0/</a>
      </li>
    </ul>
  </body>
</html>
```

Python test:

```
import zarr
zarr.group(store=zarr.storage.FSStore("http://localhost:8080/image/1.zarr/"))
```

Python output:

```
Traceback (most recent call last):
  File "./martin.py", line 17, in <module>
    print(now(), t(x)["0"][0][0][0][0][0])
  File "./martin.py", line 12, in t
    store = zarr.storage.FSStore(x, **options)
  File "/Users/jamoore/opt/zarr/zarr/storage.py", line 966, in __init__
    if self.fs.exists(url) and not self.fs.isdir(url):
  File "/Users/jamoore/opt/zarr/zarr/errors.py", line 38, in err_fspath_exists_notdir
    raise ValueError('path exists but is not a directory: %r' % fspath)
ValueError: path exists but is not a directory: 'http://localhost:8080/image/1.zarr/'
```

see: https://github.com/zarr-developers/zarr-python/pull/546#issuecomment-674112250 

cc: @mtbc

**Comment by martindurant** [comment]
Unfortunately, *all* URLs are files; I believe HTTPFileSystem should have an override for `isdir`, something like
```
def isdir(self, path):
    return bool(self.ls(path))
```
i.e., if there are any links, it is (also) a directory.
