### ISSUE TITLE
[BUG] pd.read_csv(s3_path) fails with "TypeError: 'coroutine' object is not subscriptable"

### ISSUE THREAD

**Issue by chinmaychandak** [intake/filesystem_spec#385]
Code:
```
import pandas as pd
df = pd.read_csv(s3_path)
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/parsers.py", line 431, in _read
    filepath_or_buffer, encoding, compression
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/common.py", line 185, in get_filepath_or_buffer
    filepath_or_buffer, encoding=encoding, compression=compression, mode=mode
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/s3.py", line 48, in get_filepath_or_buffer
    file, _fs = get_file_and_filesystem(filepath_or_buffer, mode=mode)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/s3.py", line 29, in get_file_and_filesystem
    file = fs.open(_strip_schema(filepath_or_buffer), mode)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 844, in open
    **kwargs
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 394, in _open
    autocommit=autocommit, requester_pays=requester_pays)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 1276, in __init__
    cache_type=cache_type)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1134, in __init__
    self.details = fs.info(path)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 719, in info
    return sync(self.loop, self._info, path, bucket, key, kwargs, version_id)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 51, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 35, in f
    result[0] = await future
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 660, in _info
    Key=key, **version_id_kw(version_id), **self.req_kw)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 214, in _call_s3
    raise translate_boto_error(err)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 207, in _call_s3
    return await method(**additional_kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/client.py", line 121, in _make_api_call
    operation_model, request_dict, request_context)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/client.py", line 140, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 90, in _send_request
    exception):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 199, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/utils.py", line 1214, in redirect_from_error
    new_region = self.get_bucket_region(bucket, response)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/utils.py", line 1272, in get_bucket_region
    headers = response['ResponseMetadata']['HTTPHeaders']
TypeError: 'coroutine' object is not subscriptable
```

I wasn't seeing this error until a couple of days ago, not sure what changed.

I installed s3fs via `conda install -c conda-forge s3fs`. When I try pinning s3fs to `0.4.2`, everything works just fine.

**Comment by martindurant** [comment]
Do you see the same with `pd.read_csv`? That would make it easier for me to debug (unless someone sends me a GPU...)
The output looks like the call failed, and it's the unwrapping of the error that is raising the exception.

**Comment by kkraus14** [comment]
The cudf codepath here will go into a call like: `fs, _, paths = fsspec.get_fs_token_paths(path)` and then seems to be failing on calling `fs.open(paths[0])`.

**Comment by martindurant** [comment]
Right, this is actually an s3fs issue, probably while doing a HEAD_OBJECT (but it can stay here)

**Comment by martindurant** [comment]
`s3fs` has a logger (called "s3fs") which will tell you the exact calls that were issued, at the DEBUG level

**Comment by chinmaychandak** [comment]
I'm really sorry about not providing a minimal reproducer before, but I have tried out a few things now.

Yes, `pd.read_csv()` fails too. I have updated the initial snippets to reflect the corresponding traceback.

Here are some of my `conda list` outputs, which I thought might be useful:

```
(rapids) root@custreamzjob-7c99fdb9f9-74hxz:/rapids# conda list boto
# packages in environment at /opt/conda/envs/rapids:
#
# Name                    Version                   Build  Channel
aiobotocore               1.1.0                      py_0    conda-forge
botocore                  1.17.44            pyh9f0ad1d_0    conda-forge

(rapids) root@custreamzjob-7c99fdb9f9-74hxz:/rapids# conda list s3fs
# packages in environment at /opt/conda/envs/rapids:
#
# Name                    Version                   Build  Channel
s3fs                      0.5.0                      py_0    conda-forge

(rapids) root@custreamzjob-7c99fdb9f9-74hxz:/rapids# conda list fsspec
# packages in environment at /opt/conda/envs/rapids:
#
# Name                    Version                   Build  Channel
fsspec                    0.8.0                      py_0    conda-forge

(rapids) root@custreamzjob-7c99fdb9f9-74hxz:/rapids# conda list dask
# packages in environment at /opt/conda/envs/rapids:
#
# Name                    Version                   Build  Channel
dask                      2.22.0                     py_0    conda-forge
dask-core                 2.22.0                     py_0    conda-forge
dask-cuda                 0.15.0a200807           py37_90    rapidsai-nightly
dask-cudf                 0.15.0a200807   py37_g5d905cf67_4034    rapidsai-nightly
dask-xgboost              0.2.0.dev28      cuda10.2py37_0    rapidsai
```

Please let me know if I can help with something else. Also, @martindurant, do you recommend moving this issue to s3fs?

**Comment by chinmaychandak** [comment]
> `s3fs` has a logger (called "s3fs") which will tell you the exact calls that were issued, at the DEBUG level

Just used this, and I see the below stacktrace, although it doesn't seem to be of much help.

```

2020-08-25 23:56:55,214 - s3fs - DEBUG - Setting up s3fs instance
2020-08-25 23:56:55,248 - s3fs - DEBUG - CALL: head_object - ({},) - {'Bucket': 'logs-bucket', 'Key': 'csv_file'}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/parsers.py", line 431, in _read
    filepath_or_buffer, encoding, compression
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/common.py", line 185, in get_filepath_or_buffer
    filepath_or_buffer, encoding=encoding, compression=compression, mode=mode
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/s3.py", line 48, in get_filepath_or_buffer
    file, _fs = get_file_and_filesystem(filepath_or_buffer, mode=mode)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/pandas/io/s3.py", line 29, in get_file_and_filesystem
    file = fs.open(_strip_schema(filepath_or_buffer), mode)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 844, in open
    **kwargs
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 394, in _open
    autocommit=autocommit, requester_pays=requester_pays)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 1276, in __init__
    cache_type=cache_type)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1134, in __init__
    self.details = fs.info(path)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 719, in info
    return sync(self.loop, self._info, path, bucket, key, kwargs, version_id)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 51, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 35, in f
    result[0] = await future
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 660, in _info
    Key=key, **version_id_kw(version_id), **self.req_kw)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 214, in _call_s3
    raise translate_boto_error(err)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 207, in _call_s3
    return await method(**additional_kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/client.py", line 121, in _make_api_call
    operation_model, request_dict, request_context)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/client.py", line 140, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 90, in _send_request
    exception):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 199, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/utils.py", line 1214, in redirect_from_error
    new_region = self.get_bucket_region(bucket, response)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/utils.py", line 1272, in get_bucket_region
    headers = response['ResponseMetadata']['HTTPHeaders']
TypeError: 'coroutine' object is not subscriptable
```

**Comment by martindurant** [comment]
The issue appears to be similar to https://github.com/aio-libs/aiobotocore/issues/707 ; something went wrong with initiating the client, and the path to get the error message is failing. You could try changing the region or auth info, as suggested in the workarounds in that issue. 

I would suggest that s3fs's code can be changed to check for this condition and extract the error message in `_call_s3`, but I would need some way to generate the error for myself to see how this would work.

**Comment by chinmaychandak** [comment]
I tried pinning the s3fs version to 0.4.2, botocore to 1.17.43 and boto3 to 1.14.43 and now I don't get this error anymore. However, I get this error:

```
File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/csv.py", line 52, in read_csv
    **kwargs,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/utils/ioutils.py", line 990, in get_filepath_or_buffer
    with fs.open(paths[0]) as f:
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 844, in open
    **kwargs
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 378, in _open
    autocommit=autocommit, requester_pays=requester_pays)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 1097, in __init__
    cache_type=cache_type)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1134, in __init__
    self.details = fs.info(path)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 530, in info
    Key=key, **version_id_kw(version_id), **self.req_kw)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 200, in _call_s3
    return method(**additional_kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/client.py", line 622, in _make_api_call
    operation_model, request_dict, request_context)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/client.py", line 641, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/endpoint.py", line 116, in create_request
    operation_name=operation_model.name)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/signers.py", line 160, in sign
    auth.add_auth(request)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/auth.py", line 357, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

Another thing to note is that I am using 2 processes w/ 2 threads each, and each of them is trying to read a file from S3. And, 3 out of the 4 succeed, and 1 fails. Not sure if this is some kind of multi-process async error. 

I will try to create a minimal reproducer soon. Although, is there a workaround here, maybe pin to an older version, because I wasn't seeing any of these issues a few days (maybe a week ago)?

> You could try changing the region or auth info, as suggested in the workarounds in that issue.

This unfortunately isn't an option, because I am not passing this info manually, but this happening through an IAM role on AWS.

**Comment by martindurant** [comment]
Hm, I can generate a NoCredentialsError without the weird coroutine thing. Perhaps you are right, and multiple threads are attempting to establish creds at the same time, and the race causes a problem (i.e., this is not the kind of error that should be possible) - or this is due to copied variables when setting up the subprocess. It should make a difference whether an S3 instance is created first in the main process/thread or not.

So there are two problems: for the coroutine thing, which can be solved with a test on the exception in _call_s3, and whatever the race is, which is probably harder.

**Comment by chinmaychandak** [comment]
> I can generate a NoCredentialsError without the weird coroutine thing.

Oh, you were able to reproduce it without multiple threads?

> this is due to copied variables when setting up the subprocess

This definitely seems like a possibility. Would you say this is happening because of an upstream change in s3fs, or something in botocore itself? Although I'm using older versions of both.

> It should make a difference whether an S3 instance is created first in the main process/thread or not.

I am also seeing that if I continue to read files in a loop, the same thread shows the NoCredentialsError. The rest of them always seem to succeed.

**Comment by martindurant** [comment]
> Oh, you were able to reproduce it without multiple threads?

Yes, by removing my credentials :)

> Would you say this is happening because of an upstream change in s3fs, or something in botocore itself?

s3fs now uses aiobotocore, so probably the client needs to be instantiated in each process - but is certainly supposed to be thread-safe.

**Comment by chinmaychandak** [comment]
> s3fs now uses aiobotocore

Hmm, I wonder why `aibotocore` isn't showing up in `conda list`.  I installed the libraries using `pip install boto3==1.14.43 botocore==1.17.43 s3fs==0.4.2`. Am I missing something?

**Comment by martindurant** [comment]
We are at 0.5.0; I am not sure what pip did to you!
0.4.2 has been out for months https://pypi.org/project/s3fs/#history

**Comment by chinmaychandak** [comment]
With `s3fs` 0.5.0 (this shows `aibotocore` as 1.1.0), I see `TypeError: 'coroutine' object is not subscriptable`, so I was trying to pin it to 0.4.2 (no aibotocore in `conda list`), which throws the `NoCredentialsError`.

**Comment by martindurant** [comment]
Right, I see. Assuming you also have a cred error that aiobotocore isn't translating, I am confused by why I can engineer a cred error with the latest s3fs. 

What I would try:
add logger debug statements into https://github.com/dask/s3fs/blob/master/s3fs/core.py#L212 to see under what conditions failure is happening, and what the state of the exception variable is - perhaps it contains this elusive coroutine that can be awaited. In fact, logging ought to be included here, generally.

**Comment by chinmaychandak** [comment]
Will give it a shot.

**Comment by chinmaychandak** [comment]
Although, it would be good to use the latest version of `s3fs`. I'm wondering if I should first try to figure out what is causing the `TypeError: 'coroutine' object is not subscriptable` when I do `pip install s3fs`. 

Because this fails with `pd.read_csv` and with the latest versions of `s3fs 0.5.0`, `aibotocore 1.1.0` and `botocore 1.17.44`.

@martindurant Would be better for visibility to create this issue in s3fs/botocore?

**Comment by martindurant** [comment]
Given https://github.com/dask/s3fs/issues/350 , have you been able to see this issue in single thread/process situations?

**Comment by martindurant** [comment]
Would you mind trying to set the `AWS_DEFAULT_REGION` env variable to the known region of your bucket? This isn't a solution, but will help figure out what to do.

**Comment by chinmaychandak** [comment]
> Given [dask/s3fs#350](https://github.com/dask/s3fs/issues/350) , have you been able to see this issue in single thread/process situations?

Yes, `TypeError: 'coroutine' object is not subscriptable` happens outside the multi-threading/multi-processing bit. The `NoCredentialsError` when I pin s3fs to `0.4.2` is the one that happens only with multiple threads.

> Would you mind trying to set the `AWS_DEFAULT_REGION` env variable to the known region of your bucket?

Just tried this, and it seems to make the error go away. :)

**Comment by martindurant** [comment]
OK, so NoCredentials will take some more experimenting with whether the client is initialised in the parent process or not, and whether the processes are forked or spawned. It may no longer be relevant in the latest release.

> it seems to make the error go away

So you can also pass this as S3FileSystem(client_kwargs={"region_name": ..}), or `storage_options={'client_kwargs': {"region_name": ..}}` when going through read_csv. Obviously this is only a workaround, not a solution: you shouldn't have to know the region beforehand.

It would be best, then, if we can recreate the bug using aiobotocore alone, and post the issue there. If you look through their github and stackoverflow, similar messages have appeared from time to time. It may depend on the exact versions of aiobotocore and botocore installed.

```
async def main():
    session = aiobotocore.get_session()
    async with session.create_client('s3') as client:
        return await client.head_object(Bucket=, Key=)

asyncio.run(main())
```

**Comment by martindurant** [comment]
I just updated to botocore 1.17.44 aiobotocore 1.1.0 - I think the issue went away?

**Comment by chinmaychandak** [comment]
> It may no longer be relevant in the latest release.

Will be trying it out shortly. Let's hope it works!

> It would be best, then, if we can recreate the bug using aiobotocore alone, and post the issue there. If you look through their github and stackoverflow, similar messages have appeared from time to time. It may depend on the exact versions of aiobotocore and botocore installed.

Yes, will try this out soon. Thanks a lot for all the help, Martin! :)

**Comment by chinmaychandak** [comment]
> OK, so NoCredentials will take some more experimenting with whether the client is initialised in the parent process or not, and whether the processes are forked or spawned. It may no longer be relevant in the latest release.

Yes, indeed this doesn't seem to happen with the latest release. All I did was inject `AWS_DEFAULT_REGION` as an env variable, and everything is back on track. :)

**Comment by chinmaychandak** [comment]
Created this: https://github.com/aio-libs/aiobotocore/issues/825

**Comment by thehesiod** [comment]
FYI aiobotocore does not support being run on multiple threads as it uses asyncio locks and not thread locks, and indeed botocore is constructed in a way that it attempts to retrieve the credentials once across all requests for a given Session.  Another concerning issue is that in aiobotocore is hard locked to a specific version of botocore so you cannot mix and match them.  If you want to use aiobotocore + botocore + boto3 you need to install boto3 via the extras in aiobotocore.  I bring this up because in this stack: https://github.com/intake/filesystem_spec/issues/385#issuecomment-680326826 it seems to point to the latest aiobotocore, but a mis-matched botocore, given that `aiobotocore/client.py", line 140, in _make_request` matches latest aiobotocore, but this: `botocore/utils.py", line 1214, in redirect_from_error` does not match botocore `1.17.44`: https://github.com/boto/botocore/blob/1.17.44/botocore/auth.py given the file doesn't even have that many lines

**Comment by martindurant** [comment]
The event loop executing boto calls is in its own dedicated thread in s3fs, so this should not be a problem (except for those who provide their own loop, which is "expert" mode, and does not apply here)

**Comment by chinmaychandak** [comment]
Fixed by https://github.com/aio-libs/aiobotocore/pull/827
