### ISSUE TITLE
HTTP block download failure with caching when content is gzipped

### ISSUE THREAD

**Issue by ian-r-rose** [intake/filesystem_spec#389]
Similar line of investigation as #388, but a distinct issue. I'm running into an issue with the block downloading from an HTTP source when the server tries to serve gzip-encoded data. A minimal example:

```python
import fsspec

path = "simplecache::https://opendata.arcgis.com/datasets/d3cd48afaacd4913b923fd98c6591276_36.zip"

storage_options = {
    "simplecache": {
        "cache_storage": "/tmp/cachetest/",
    }
}

with fsspec.open(path, "rb", **storage_options) as f:
    data = f.read()
```
produces
```
Traceback (most recent call last):
  File "test-cache.py", line 16, in <module>
    with fsspec.open(path, "rb", **storage_options) as f:
  File "filesystem_spec/fsspec/core.py", line 101, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "filesystem_spec/fsspec/implementations/cached.py", line 371, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "filesystem_spec/fsspec/spec.py", line 839, in open
    f = self._open(
  File "filesystem_spec/fsspec/implementations/cached.py", line 371, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "filesystem_spec/fsspec/implementations/cached.py", line 562, in _open
    data = f.read(f.blocksize)
  File "filesystem_spec/fsspec/implementations/http.py", line 339, in read
    return super().read(length)
  File "filesystem_spec/fsspec/spec.py", line 1310, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "filesystem_spec/fsspec/caching.py", line 38, in _fetch
    return self.fetcher(start, stop)
  File "filesystem_spec/fsspec/asyn.py", line 100, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "filesystem_spec/fsspec/asyn.py", line 80, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "filesystem_spec/fsspec/asyn.py", line 51, in sync
    raise exc.with_traceback(tb)
  File "filesystem_spec/fsspec/asyn.py", line 35, in f
    result[0] = await future
  File "filesystem_spec/fsspec/implementations/http.py", line 376, in async_fetch_range
    out = await r.read()
  File "lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "lib/python3.8/site-packages/aiohttp/streams.py", line 334, in read
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: gzip'
```

Note that the file itself is not gzipped, this is in the HTTP transport layer.

Weirdly enough, this seems to happen upon downloading the *second* block of data, the first gets decoded just fine, so this only appears for files that are larger than the default block size. I'm not sure what the cause of that is just yet.

I can fix the above issue by either disabling the blocking (`http={"block_size": 0}`), or by requesting no gzip-encoding from the server (`http={ "headers": { "Accept-Encoding": "identity" } }`), but both of these are lower-level fixes than I'd like to point users at.

**Comment by martindurant** [comment]
The zip file is being gzip encoded? It seems to me that avoiding the compression is exactly the right thing to do.

There have been MANY issues with server implementation, since the "standards" are unclear on every point.

I assume that the server is serving the gzipped bytes, and respecting the range header - so the second block start mid-gzip block. aiohttp should *not* be attempting to decompress this.

As far as I understand, content-encoding of gzip means that you have a file that is, and should remain, compressed. It is not the same as transfer-encoding (which is just a contract between server and client). The client has a `auto_decompress` which could be off; but I don't know if in some situations this would mean the number of bytes you get is not the number you asked for.

Note the comment [here](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/cached.py#L565) (which is *not* the block you are hitting, because the server must at least have given the size). There is an argument that simplecache should always call `_get_file` ([http implementation](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/http.py#L150)) to get around this kind of weirdness.

**Comment by ian-r-rose** [comment]
> There have been MANY issues with server implementation, since the "standards" are unclear on every point.

Yep, I have also run into issues around gzipping with specifically Esri/ArcGIS servers before -- they are often not particularly reliable implementers of standards.

> I assume that the server is serving the gzipped bytes, and respecting the range header - so the second block start mid-gzip block. aiohttp should _not_ be attempting to decompress this.

This is correct, as far as I have been able to tell.

> There is an argument that simplecache should always call `_get_file` ([http implementation](https://github.com/intake/filesystem_spec/blob/master/fsspec/implementations/http.py#L150)) to get around this kind of weirdness.

I would be in favor of making `simplecache` as simple as possible. Although being able to specify `headers` or `block_size` as defaults as you suggest with #339 would also go a long way to fixing this.

In the meantime I'm happy to use the above fixes of either avoiding compression or reading in a single block.

**Comment by ian-r-rose** [comment]
I should also note that when there is a failure to download a block for the cache, it can leave that cache in a broken state, with partially downloaded content masquerading as full-downloaded content. Clearing the cache fixes it, but it can result in unexpected errors in the meantime.

Happy to close if you feel this is working as intended, or if there is nothing to be done on this end.

**Comment by martindurant** [comment]
I think the caching system could do with more checks and safeguards. If you use wholefilecache instead of simplecache, you can check against the server to see if the file-size is as expected upon each open (this, of course, costs a call, and is information that should already be known)

**Comment by martindurant** [comment]
(it would make all kinds of sense to have the open method try/except and delete the file on disc upon exception or if the size didn't match)

**Comment by martindurant** [comment]
With https://github.com/intake/filesystem_spec/pull/394 , cache downloading uses `get` instead of `read(x)`, so the issue should go away..

**Comment by ian-r-rose** [comment]
Hmm, I still see the same issue on master (disabling blocking or setting the headers as above are still functional workarounds though).

**Comment by martindurant** [comment]
Maybe this only works with the multi-context:
```
with fsspec.open_files(path, "rb", **storage_options) as files:
    data = files[0].read()
```

**Comment by ian-r-rose** [comment]
> Maybe this only works with the multi-context:
> 
> ```
> with fsspec.open_files(path, "rb", **storage_options) as files:
>     data = files[0].read()
> ```
Yep, I can confirm that the issue doesn't appear here.

**Comment by martindurant** [comment]
OK, an improvement! :)

**Comment by albertvillanova** [comment]
Hi, any update on this issue?

**Comment by ian-r-rose** [comment]
No updates from my end, but have you tried the above workarounds for `block_size: 0` or the http headers @albertvillanova ?

**Comment by albertvillanova** [comment]
Thank you. The issue is avoided when passing `block_size: 0`. Is this solution optimal?

**Comment by martindurant** [comment]
> Is this solution optimal?

It has no downside, if you don't use random access (read from beginning to end)
