### ISSUE TITLE
Deadlock when running alongside a dask client: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by PedroMDuarte** [intake/filesystem_spec#424]
Running into a problem when using `GCSFileSystem` along with a dask client. The dask client starts an IO loop, fsspec attempts to start another loop and that causes a runtime error in a thread: 

```
Traceback (most recent call last): File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner self.run() 
    File "/usr/local/lib/python3.7/threading.py", line 870, in run self._target(*self._args, **self._kwargs) 
    File "/usr/local/lib/python3.7/asyncio/base_events.py", line 528, in run_forever 'Cannot run the event loop while another loop is running') 
    RuntimeError: Cannot run the event loop while another loop is running
```

The error in fsspec then causes the dask client to block forever. 

I believe the exception is coming from trying to start [this thread](https://github.com/intake/filesystem_spec/blob/master/fsspec/asyn.py#L138).

There are more details here: https://github.com/dask/distributed/issues/4124

**Comment by martindurant** [comment]
Closing in favour of discussion on the distributed issue
