### ISSUE TITLE
CachingFileSystem.save_cache might fail with KeyError if multiple processes accessing cache:

### ISSUE THREAD

**Issue by gerritholl** [intake/filesystem_spec#471]
When I'm running multiple scripts that all use a `CachingFileSystem` with the same directory but not accessing the same cached files, sometimes  `CachingFileSystem.save_cache` fails with a `KeyError`:

This code:

```python
import s3fs, fsspec.implementations.cached
fs_s3 = s3fs.S3FileSystem(anon=True)
cache_storage_block = "/media/x22264/cache/ABI-block-cache/"
fs_block = fsspec.implementations.cached.CachingFileSystem(
        fs=fs_s3,
        cache_storage=cache_storage_block,
        cache_check=600,
        check_files=False,
        expiry_times=False,
        same_names=False)
fs_block.open(
        "noaa-goes16/ABI-L1b-RadM/2019/152/00/OR_ABI-L1b-RadM1-M6C10_G16_s20191520028490_e20191520028559_c20191520028584.nc",
        block_size=65536)
```

sometimes, but not always, fails with:

```
Traceback (most recent call last):
  File "mwe106.py", line 11, in <module>
    fs_block.open(
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 376, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/spec.py", line 897, in open
    f = self._open(
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 376, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 327, in _open
    self.save_cache()
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 376, in <lambda>
    return lambda *args, **kw: getattr(type(self), item)(self, *args, **kw)
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 158, in save_cache
    if cache[k]["blocks"] is True:
KeyError: 'noaa-goes16/ABI-L1b-RadM/2019/152/00/OR_ABI-L1b-RadM1-M6C08_G16_s20191520040519_e20191520040576_c20191520041017.nc'
Exception ignored in: <function AbstractBufferedFile.__del__ at 0x7f3a452814c0>
Traceback (most recent call last):
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/spec.py", line 1505, in __del__
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 326, in <lambda>
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 376, in <lambda>
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 342, in close_and_update
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 376, in <lambda>
  File "/opt/pytroll/pytroll_inst/miniconda3-exp/envs/py38/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 154, in save_cache
NameError: name 'open' is not defined
```

Just now I ran this script six times.  It succeeded three times and failed three times.  At the same times, three other processes were running on the same machine, that were occasionally (but not continuously) accessing the same blockcache, but not the same files.

I noticed there is a comment relating to file locking in the source code:

https://github.com/intake/filesystem_spec/blob/e5ca6a82d7c74c4b7fe3301c0a526142e84ebb13/fsspec/implementations/cached.py#L150-L151

Perhaps accessing the same blockcache from multiple processes is simply not supported at the moment, in which case this is a feature request.  If it's supposed to work then this issue may be considered a bug report.  Either way, I would welcome possibly work-arounds (one work-around would be for each process to have its own cache directory, but that makes it difficult to re-use a cache, which somewhat defeats the point of the on-disk cache).

As a side-issue, there is also still an ignored exception in `AbstractBufferedFile.__del__`, despite the closure of the related issue #404.

**Comment by martindurant** [comment]
There is indeed a single file containing the caching information, which is updated time-to-time by each instance accessing the directory. The intent is, as stated in the comment, that this might cause rereads sometimes, but should not fail - so I would say this is a bug.

I believe the following fixes it:
```diff
--- a/fsspec/implementations/cached.py
+++ b/fsspec/implementations/cached.py
@@ -155,7 +155,7 @@ class CachingFileSystem(AbstractFileSystem):
                 cached_files = pickle.load(f)
             for k, c in cached_files.items():
                 if c["blocks"] is not True:
-                    if cache[k]["blocks"] is True:
+                    if k in cache and cache[k]["blocks"] is True:
                         c["blocks"] = True
                     else:
                         c["blocks"] = set(c["blocks"]).union(cache[k]["blocks"])
```
but I have not thought of a way to add a test for this.

**Comment by martindurant** [comment]
The fix (or silencing) for del would look like
```diff
@@ -339,7 +339,12 @@ class CachingFileSystem(AbstractFileSystem):
         c = self.cached_files[-1][path]
         if c["blocks"] is not True and len(["blocks"]) * f.blocksize >= f.size:
             c["blocks"] = True
-        self.save_cache()
+        try:
+            self.save_cache()
+        except IOError:
+            logger.debug("Cache saving failed while closing file")
+        except NameError:
+            logger.debug("Cache save failed due to interpreter shutdown")
         close()
```
The first condition could be simulated b making the cache metadata file read-only. It's the second condition that you are seeing though - perhaps monkeypatch could be used to make  `open` in the module to raise a `NameError`.
