### ISSUE TITLE
AttributeError: '_io.BufferedReader' object has no attribute 'temp'

### ISSUE THREAD

**Issue by espdev** [intake/filesystem_spec#531]
Hello,

I try to use `LocalFileSystem` with Transaction context manager and I get the following error:

```
AttributeError: '_io.BufferedReader' object has no attribute 'temp'
```

An example:

```python
from fsspec.implementations.local import LocalFileSystem

def main():
    fs = LocalFileSystem()

    with fs.transaction:
        with fs.open('test.txt', 'w') as fp:
            fp.write('hello')

        with fs.open('test.txt', 'r') as fp:
            s = fp.read()
        
        print(s)

if __name__ == '__main__':
    main()
```

An exception:

```
Traceback (most recent call last):
  File "scratches\scratch_94.py", line 18, in <module>
    main()
  File "scratches\scratch_94.py", line 14, in main
    print(s)
  File "lib\site-packages\fsspec\transaction.py", line 24, in __exit__
    self.complete(commit=exc_type is None)
  File "lib\site-packages\fsspec\transaction.py", line 37, in complete
    f.commit()
  File "lib\site-packages\fsspec\implementations\local.py", line 246, in commit
    os.replace(self.temp, self.path)
  File "lib\site-packages\fsspec\implementations\local.py", line 261, in __getattr__
    return getattr(self.f, item)
AttributeError: '_io.BufferedReader' object has no attribute 'temp'
```

If I only use write operations within transaction context it works but read operation leads to the exception.

**Comment by andersy005** [comment]
I think this is a bug. It appears that `self.temp` is set in this code path in `_open`

https://github.com/intake/filesystem_spec/blob/fb406453b6418052f98b64d405bd4e6a4be1def1/fsspec/implementations/local.py#L200-L209

Inspecting `self` right before the failing `os.replace(self.temp, self.path)` call reveals that the code path that sets `self.temp` isn't being reached:

```python
> /Users/abanihi/opt/miniconda3/envs/playground/lib/python3.8/site-packages/fsspec/implementations/local.py(246)commit()
    244         if self.autocommit:
    245             raise RuntimeError("Can only commit if not already set to autocommit")
--> 246         os.replace(self.temp, self.path)
    247
    248     def discard(self):

ipdb> self
<fsspec.implementations.local.LocalFileOpener object at 0x7fa9f92021c0>
ipdb> dir(self)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__fspath__', '__ge__', '__getattr__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_fetch_range', '_open', 'autocommit', 'blocksize', 'commit', 'details', 'discard', 'f', 'fs', 'mode', 'path', 'size']
ipdb> 'temp' in dir(self)
False
```

**Comment by martindurant** [comment]
I believe the case of files being opened for reading within a transaction has never been attempted. The following probably solves it:
```diff
--- a/fsspec/spec.py
+++ b/fsspec/spec.py
@@ -942,7 +942,7 @@ class AbstractFileSystem(up, metaclass=_Cached):
                 cache_options=cache_options,
                 **kwargs
             )
-            if not ac:
+            if not ac and 'r' not in mode:
                 self.transaction.files.append(f)
             return f
```

**Comment by andersy005** [comment]
> The following probably solves it: 

Not quite :(  If my interpretation is correct, it appears that the file is being deleted before we have a chance of opening it: 

<details>
<summary>Details</summary>

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-6d4722f3441e> in <module>
      3     with fs.open(file, 'w') as fp:
      4         fp.write('hello')
----> 5     with fs.open(file, 'r') as fp:
      6         s = fp.read()
      7     print(s)

~/devel/intake/filesystem_spec/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    931             }
    932             return io.TextIOWrapper(
--> 933                 self.open(path, mode, block_size, **kwargs), **text_kwargs
    934             )
    935         else:

~/devel/intake/filesystem_spec/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    935         else:
    936             ac = kwargs.pop("autocommit", not self._intrans)
--> 937             f = self._open(
    938                 path,
    939                 mode=mode,

~/devel/intake/filesystem_spec/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
    115         if self.auto_mkdir and "w" in mode:
    116             self.makedirs(self._parent(path), exist_ok=True)
--> 117         return LocalFileOpener(path, mode, fs=self, **kwargs)
    118 
    119     def touch(self, path, **kwargs):

~/devel/intake/filesystem_spec/fsspec/implementations/local.py in __init__(self, path, mode, autocommit, fs, **kwargs)
    197         self.autocommit = autocommit
    198         self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 199         self._open()
    200 
    201     def _open(self):

~/devel/intake/filesystem_spec/fsspec/implementations/local.py in _open(self)
    202         if self.f is None or self.f.closed:
    203             if self.autocommit or "w" not in self.mode:
--> 204                 self.f = open(self.path, mode=self.mode)
    205             else:
    206                 # TODO: check if path is writable?

FileNotFoundError: [Errno 2] No such file or directory: '/Users/abanihi/devel/intake/filesystem_spec/test.txt'
> /Users/abanihi/devel/intake/filesystem_spec/fsspec/implementations/local.py(204)_open()
    202         if self.f is None or self.f.closed:
    203             if self.autocommit or "w" not in self.mode:
--> 204                 self.f = open(self.path, mode=self.mode)
    205             else:
    206                 # TODO: check if path is writable?
```

</details>

**Comment by martindurant** [comment]
On reflection: 
- yes, I think my change is the right one
- the original code *should not work*: the file "temp.txt" has not been finalised, so you should not be able to read it.

**Comment by andersy005** [comment]
> the original code should not work: the file "temp.txt" has not been finalised, so you should not be able to read it. 

Aha! That's it... Thank you for the clarification! I hadn't payed attention to the location of the read context manager.

**Comment by andersy005** [comment]
I'm opening a PR with your changes shortly
