### ISSUE TITLE
Handling errors that happened on the _initiate_upload separately

### ISSUE THREAD

**Issue by isidentical** [intake/filesystem_spec#573]
When opening a subclass of the AbstractBufferedFile, there might be some problems happening in the `_initiate_upload` function. Which would result in the absence of the necessary logic to finalize the upload. Here is a short example from s3fs;
```
with fs.open('test/foo/bar', 'wb') as stream:
    stream.write(b'x' * stream.blocksize)
```
If the `test` is a bucket that actually doesn't exist, we get a really weird and cryptic error
```
Traceback (most recent call last):
  File "/home/isidentical/s3fs/s3fs/core.py", line 235, in _call_s3
    return await method(**additional_kwargs)
  File "/home/isidentical/.venv38/lib/python3.8/site-packages/aiobotocore/client.py", line 154, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchBucket: An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "t1.py", line 8, in <module>
    stream.write(b'x' * stream.blocksize)
  File "/home/isidentical/filesystem_spec/fsspec/spec.py", line 1360, in write
    self.flush()
  File "/home/isidentical/filesystem_spec/fsspec/spec.py", line 1395, in flush
    self._initiate_upload()
  File "/home/isidentical/s3fs/s3fs/core.py", line 1600, in _initiate_upload
    self.mpu = self._call_s3(
  File "/home/isidentical/s3fs/s3fs/core.py", line 1592, in _call_s3
    return self.fs.call_s3(method, self.s3_additional_kwargs, *kwarglist, **kwargs)
  File "/home/isidentical/filesystem_spec/fsspec/asyn.py", line 121, in wrapper
    return maybe_sync(func, self, *args, **kwargs)
  File "/home/isidentical/filesystem_spec/fsspec/asyn.py", line 100, in maybe_sync
    return sync(loop, func, *args, **kwargs)
  File "/home/isidentical/filesystem_spec/fsspec/asyn.py", line 71, in sync
    raise exc.with_traceback(tb)
  File "/home/isidentical/filesystem_spec/fsspec/asyn.py", line 55, in f
    result[0] = await future
  File "/home/isidentical/s3fs/s3fs/core.py", line 253, in _call_s3
    raise translate_boto_error(err)
FileNotFoundError: The specified bucket does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t1.py", line 8, in <module>
    stream.write(b'x' * stream.blocksize)
  File "/home/isidentical/filesystem_spec/fsspec/spec.py", line 1557, in __exit__
    self.close()
  File "/home/isidentical/filesystem_spec/fsspec/spec.py", line 1524, in close
    self.flush(force=True)
  File "/home/isidentical/filesystem_spec/fsspec/spec.py", line 1397, in flush
    if self._upload_chunk(final=force) is not False:
  File "/home/isidentical/s3fs/s3fs/core.py", line 1717, in _upload_chunk
    UploadId=self.mpu["UploadId"],
TypeError: 'NoneType' object is not subscriptable
```

The reason seems to be that, no matter what kind of exception happened `__exit__` tries to close the file but since `_initate_upload` failed previously, the expectations of closing logic doesn't get satisfiedied;
https://github.com/intake/filesystem_spec/blob/3c6f9eae0d1516308b35ef9bec4548cf04ce164e/fsspec/spec.py#L1559-L1560

This could be overriden in the implementation by just holding a state like `initalized: bool = False` and checking this before `_upload_chunk` calls. Though it might be eaiser for all implementations if this  would be hosted in the fsspec itself, perhaps by guarding the functions in the AbstractBufferedFile level;
```py
    def initiate_upload(self, *args, **kwargs):
        self._initiate_upload(self, *args, **kwargs)
        self.initiated = True
    
    def upload_chunk(self, *args, **kwargs):
        if not self.initiated:
            return None
        self._upload_chunk(self, *args, **kwargs)
```

**Comment by martindurant** [comment]
Yes, I think handling this is a good idea. I would suggest that a file that failed to open at the initiate stage be marked as `closed`, and that subsequent attempt to do anything raise "IO operation on a closed file" (but `__exit__` calls `close` and the file is already closed, so that's OK).

I think this is better than a no-op for `upload_chunk`, since a file doesn't necessarily get used with a context, and it would be weird/wrong to seem like writes were still succeeding following the initial error.
