### ISSUE TITLE
FTP cannot handle partial reads

### ISSUE THREAD

**Issue by qwertystop** [intake/filesystem_spec#641]
Any attempt to use an FTP-backed file object for something that reads less than the entire file fails, with the following stacktrace:

Stacktrace:
```
Traceback (most recent call last):
  File "/home/qwertystop/.pyenv/versions/hmcc-invdb/lib/python3.7/site-packages/fsspec/implementations/ftp.py", line 251, in _fetch_range
    callback=callback,
  File "/home/qwertystop/.pyenv/versions/3.7.4/lib/python3.7/ftplib.py", line 447, in retrbinary
    callback(data)
  File "/home/qwertystop/.pyenv/versions/hmcc-invdb/lib/python3.7/site-packages/fsspec/implementations/ftp.py", line 239, in callback
    raise TransferDone
fsspec.implementations.ftp.TransferDone

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qwertystop/.pyenv/versions/hmcc-invdb/lib/python3.7/site-packages/fsspec/implementations/ftp.py", line 256, in _fetch_range
    self.fs.ftp.abort()
  File "/home/qwertystop/.pyenv/versions/3.7.4/lib/python3.7/ftplib.py", line 267, in abort
    raise error_proto(resp)
ftplib.error_proto: 150 0.193 seconds (measured here), 1.29 Mbytes per second

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sync_db.py", line 412, in <module>
    sync()
  File "sync_db.py", line 408, in sync
    send_to_db(files, tablename, colspec, conf["psql"], args.init, args.product)
  File "sync_db.py", line 299, in send_to_db
    header = next(reader)
  File "/home/qwertystop/.pyenv/versions/hmcc-invdb/lib/python3.7/site-packages/fsspec/spec.py", line 1449, in read
    out = self.cache._fetch(self.loc, self.loc + length)
  File "/home/qwertystop/.pyenv/versions/hmcc-invdb/lib/python3.7/site-packages/fsspec/caching.py", line 153, in _fetch
    self.cache = self.fetcher(start, end)  # new block replaces old
  File "/home/qwertystop/.pyenv/versions/hmcc-invdb/lib/python3.7/site-packages/fsspec/implementations/ftp.py", line 259, in _fetch_range
    self.fs.ftp._connect()
AttributeError: 'FTP' object has no attribute '_connect'
```

I initially suspected this to be a simple typo; changing `self.fs.ftp._connect()` to `self.fs.connect()` at line 259 of `ftp.py` is at least sufficient to prevent this specific error. However, at that point, the connection attempt reliably times out when I attempt to read an `FTPFile` through `csv.reader`, so I am unsure whether the issue is more complicated than that; I don't know enough of the FTP spec to judge that.

**Comment by martindurant** [comment]
You are right, that whereas the filesystem has a `_connect`, the underlying FTP object's corresponding method is called `connect` (no underscore).  The line should have read:
```
self.fs._connect()
```

However, this line only fires on an error condition (which is why no one noticed before), and that error seems to be that `abort` - called to halt the in-progress transfer - isn't succeeding. You might want to check in the FTP server's logs, if possible, or perhaps you can get something about the state of the connection with ` debug`. Unfortunately, there are many many flavours of FTP server, and it's possible that partial downloads are simply not allowed.

 FTPFileSystem really ought to have more logging to let you know what's going on.

**Comment by qwertystop** [comment]
Thank you for that bit of guidance. Perhaps, as a fallback, it would be useful to have a "pull entire file to local buffer" option? That is, if you can't abort the connection, let it finish?

**Comment by martindurant** [comment]
I would care to bet (but please do try it), that after an attempted abort, the connection is left in an unstable and unusable state. Certainly, the python side will no longer be expecting more data.
