### ISSUE TITLE
https://github.com/intake/filesystem_spec/commit/2eb83d0cf35f1a91494254574df07653fae043d6

### ISSUE THREAD

**Issue by AndreiBarsan** [intake/filesystem_spec#793]
`mkdir` ignores `exist_ok` on the local filesystem. `makedirs` works fine but obviously is not a replacement if we want `create_parents=False`.

Actual behavior: `mkdir` fails to create an existing directory when `exist_ok=True`.
Expected behavior: `mkdir` should not care that the dir exists if `exist_ok=True`

Example:
```
╰─➤  python                                                                                                                                                                     1 ↵
import Python 3.8.7 (default, Sep 16 2021, 16:26:33)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fsspec
>>> fs = fsspec.filesystem("file")
>>> print(fsspec.__version__)
2021.10.0
>>> fs.mkdir("/tmp/poodle")
>>> fs.mkdir("/tmp/poodle")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrei/.waabi/av_venv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 39, in mkdir
    raise FileExistsError(path)
FileExistsError: /tmp/poodle
>>> fs.mkdir("/tmp/poodle", exist_ok=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrei/.waabi/av_venv/lib/python3.8/site-packages/fsspec/implementations/local.py", line 39, in mkdir
    raise FileExistsError(path)
FileExistsError: /tmp/poodle
```

Seems like this bug was introduced by [this commit](https://github.com/intake/filesystem_spec/commit/2eb83d0cf35f1a91494254574df07653fae043d6)

**Comment by martindurant** [comment]
I would say that the first exception is correct behaviour, but mkdirs should also work. Would you care to provide a fix and test?

**Comment by martindurant** [comment]
On closer reading...
`mkdir` does not support `exit_ok` on any implementation, only `makedirs` does! It appears that your code behaves as it ought.
