### ISSUE TITLE
error when reading empty file using CachingFileSystem

### ISSUE THREAD

**Issue by ophiry** [intake/filesystem_spec#90]
example:
```
from fsspec.implementations.cached import CachingFileSystem
fs = CachingFileSystem(target_protocol='s3')
fs.open('s3://bucket/empty')

```
```
{'fn': '01c8b40c487e3c79a7549715f6fff04a15e6b0017bcb83cb98d9278b0b4ed4ec', 'blocks': set()}
Traceback (most recent call last):
  File "/fsspec_test.py", line 3, in <module>
    fs.open('s3://bucket/empty')
  File "/usr/local/miniconda3/envs//lib/python3.7/site-packages/fsspec/implementations/cached.py", line 157, in <lambda>
    self, *args, **kw
  File "/usr/local/miniconda3/envs//lib/python3.7/site-packages/fsspec/spec.py", line 669, in open
    autocommit=ac, **kwargs)
  File "/usr/local/miniconda3/envs//lib/python3.7/site-packages/fsspec/implementations/cached.py", line 157, in <lambda>
    self, *args, **kw
  File "/usr/local/miniconda3/envs//lib/python3.7/site-packages/fsspec/implementations/cached.py", line 132, in _open
    fn, blocks)
  File "/usr/local/miniconda3/envs//lib/python3.7/site-packages/fsspec/core.py", line 397, in __init__
    self.cache = self._makefile()
  File "/usr/local/miniconda3/envs//lib/python3.7/site-packages/fsspec/core.py", line 409, in _makefile
    fd.seek(self.size - 1)
OSError: [Errno 22] Invalid argument
```

**Comment by martindurant** [comment]
:) I suppose caching *should* break when trying to cache an empty file. But seriously, this should be a simple fix, if you'd like to provide it (with a test).
